turris-news: add cron command

diff --git a/turris-news b/turris-news
--- a/turris-news
+++ b/turris-news
@@ -308,9 +308,43 @@ op_read() {
 	fi
 }
 
+# Handle single channel for cron operation
+# As argument is passed name of channel
+_cron_channel() {
+	is_channel "$1" || return 0 # Ignore invalid channels
+	grep "^[^:]\+:" "$TMP_STORE/$1.index" | while read LN; do
+		if _news_not_read "$1" "$LN"; then
+			# Note: markdown hard expected!!
+			MSG="$(_read_news "$1" "$LN" | tail -n +2)" || continue # Ignore failed
+			# TODO translations (probably wait for new notification system)
+			create_notification -s news 'Česká verze prozatím není podporovaná.' "$MSG"
+		fi
+	done
+}
+
 op_cron() {
-	# TODO
-	exit 12
+	for ARG in "$@"; do
+		case "$ARG" in
+			-h|--help)
+				echo "Usage: turris-news cron"
+				echo "Turris news update indexes and generate notification for all new news."
+				echo "This execution can be configured using uci with following options:"
+				echo "This is intended to be called only from cron!"
+				exit 0
+				;;
+			-a|--all)
+				ALL=true
+				;;
+		esac
+	done
+	local ENABLED
+	config_get_bool ENABLED cron enabled 0
+	if [ "$ENABLED" != "1" ]; then
+		echo "turris-news cron not enabled" >&2
+		return 1
+	fi
+	index_update # TODO update only enabled indexes (but currently that is not big overhead)
+	config_list_foreach cron channel _cron_channel
 }
 
 
